# 기반 이미지 설정 (Python 3.8을 사용하는 공식 Python 이미지)
FROM python:3.11

# 작업 디렉토리를 /app으로 설정
WORKDIR /app

# 호스트 시스템의 현재 디렉토리에 있는 모든 파일을 컨테이너의 /app 디렉토리로 복사
COPY ./Client /app/Client

# 필요한 패키지들을 설치하기 위해 requirements.txt를 복사하고 의존성 설치
COPY ./Client/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# PYTHONPATH 설정
ENV PYTHONPATH /app


# 앱 실행을 위한 명령
#CMD ["python", "Client/main.py"]
CMD ["tail", "-f", "/dev/null"]

# pip freeze > requirements.txt