apiVersion: v1
kind: Pod
metadata:
  name: tcp-client-1
spec:
  containers:
  - name: tcp-client-1
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "TCP"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8082"
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-client-2
spec:
  containers:
  - name: tcp-client-2
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "TCP"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8082"
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-client-3
spec:
  containers:
  - name: tcp-client-3
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "TCP"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8082"
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-client-4
spec:
  containers:
  - name: tcp-client-4
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "TCP"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8082"
---
apiVersion: v1
kind: Pod
metadata:
  name: api-client-1
spec:
  containers:
  - name: api-client-1
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "API"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8081"
---
apiVersion: v1
kind: Pod
metadata:
  name: api-client-2
spec:
  containers:
  - name: api-client-2
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "API"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8081"
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-client-1
spec:
  containers:
  - name: udp-client-1
    image: distributed-system-client:1.3
    env:
      - name: SERVER_TYPE
        value: "UDP"
      - name: SERVER_IP
        value: "load-balancer-service"
      - name: SERVER_PORT
        value: "8083"
