apiVersion: v1
kind: Pod
metadata:
  name: load-balancer
  labels:
    app: load-balancer
spec:
  containers:
  - name: load-balancer
    image: distributed-system-load-balancer:7.9
    ports:
      - containerPort: 27017
    env:
      - name: CONTROL_SERVER_PORT
        value: "8080"
      - name: ROUTING_RULE
        value: "user_count"
      - name: HEALTH_CHECK_PORT
        value: "8080"
      - name: HEALTH_CHECK_BOUND
        value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  selector:
    app: load-balancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: control-server
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: forward-server-api
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: forward-server-tcp
  - protocol: TCP
    port: 8083
    targetPort: 8083
    name: forward-server-udp
---
apiVersion: v1
kind: Pod
metadata:
  name: api-server-1
spec:
  containers:
  - name: api-server-1
    image: distributed-system-service:3.1
    env:
      - name: SERVICE_TYPE
        value: "API"
      - name: SERVICE_PORT
        value: "8081"
      - name: CONTROL_SERVER_IP
        value: "load-balancer-service"
      - name: CONTROL_SERVER_PORT
        value: "8080"
      - name: HEALTH_CHECK_PORT
        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-1-service
spec:
  selector:
    app: api-server-1-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: healthz-server
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: api-server
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server-1
spec:
  containers:
  - name: tcp-server-1
    image: distributed-system-service:3.1
    env:
      - name: SERVICE_TYPE
        value: "TCP"
      - name: SERVICE_PORT
        value: "8082"
      - name: CONTROL_SERVER_IP
        value: "load-balancer-service"
      - name: CONTROL_SERVER_PORT
        value: "8080"
      - name: HEALTH_CHECK_PORT
        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-1-service
spec:
  selector:
    app: tcp-server-1-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: healthz-server
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: tcp-1-server
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server-2
spec:
  containers:
  - name: tcp-server-2
    image: distributed-system-service:3.1
    env:
      - name: SERVICE_TYPE
        value: "TCP"
      - name: SERVICE_PORT
        value: "8082"
      - name: CONTROL_SERVER_IP
        value: "load-balancer-service"
      - name: CONTROL_SERVER_PORT
        value: "8080"
      - name: HEALTH_CHECK_PORT
        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-2-service
spec:
  selector:
    app: tcp-server-2-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: healthz-server
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: tcp-2-server
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-server-1
spec:
  containers:
  - name: udp-server-1
    image: distributed-system-service:3.1
    env:
      - name: SERVICE_TYPE
        value: "UDP"
      - name: SERVICE_PORT
        value: "8083"
      - name: CONTROL_SERVER_IP
        value: "load-balancer-service"
      - name: CONTROL_SERVER_PORT
        value: "8080"
      - name: HEALTH_CHECK_PORT
        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: udp-server-service-1
spec:
  selector:
    app: udp-server-service-1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: healthz-server
  - protocol: TCP
    port: 8083
    targetPort: 8083
    name: udp-server